In [ ]:
import cv2
import numpy

In [ ]:
# read image
src = cv2.imread('../resources/python.png', cv2.IMREAD_UNCHANGED)

In [ ]:
# apply guassian blur on src image
dst = cv2.GaussianBlur(src,(5,5),cv2.BORDER_DEFAULT)

In [ ]:
# display input and output image
cv2.imshow("Gaussian Smoothing",numpy.hstack((src, dst)))

In [4]:
#Apply a Gaussian filter
from scipy.ndimage import gaussian_filter

In [5]:
# Define sigma for gausiaan filter
sigma = 0.2

In [7]:
# print gausian filter
print (gaussian_filter([[0, 0, 10, 10],
                       [0, 0, 0, 8],
                       [4, 5, 0, 0]], sigma))

[[0 0 8 9]
 [0 0 0 6]
 [3 3 0 0]]


In [8]:
print (gaussian_filter([[0, 0, 10, 10],
                       [0, 0, 0, 8],
                       [4, 5, 0, 0]], sigma, mode="constant"))

[[0 0 8 8]
 [0 0 0 6]
 [2 3 0 0]]


In [9]:
print (gaussian_filter([[0, 0, 10, 10],
                       [0, 0, 0, 8],
                       [4, 5, 0, 0]], sigma, mode="wrap"))

[[0 0 8 8]
 [0 0 0 6]
 [2 3 0 0]]
