In [1]:
# Here I will demontrate numpy image manipulation
import matplotlib.image as mpimg
import numpy as np

In [6]:
# Read in the image
image = mpimg.imread('../resources/test.jpg')

In [4]:
# You can access a pixel value by its row and column coordinates. For RGB image, 
# it returns an array of Blue, Green, Red values. For example for the Pixel of (x,y) = (100,100) the RGB value would be folllowing
px = image[100,100]
print(px)

[138 201 236]


In [9]:
# Copy the image , so that we can modify it
img = np.copy(image)

In [17]:
# You can modify the pixel values the same way. Modifying (100,100) pixel to all (255,255,255)
img[100,100] = [155,255,100]
print(img[100,100])

[155 255 100]


In [18]:
# accessing only blue,red and green pixel from the image. 2 for Red, 1 for Green, 0 for Blue
red = img[100,100,2]
print (red)
green = img[100,100,1]
print (green)
blue = img[100,100,0]
print (blue)

100
255
155


In [19]:
# modifying RED value
img.itemset((10,10,2),100)
img.item(10,10,2)

100

In [21]:
# Shape of image is accessed by img.shape. It returns a tuple of number of rows, columns and channels (if image is color)
# If image is grayscale, tuple returned contains only number of rows and columns.
print (img.shape)

(540, 960, 3)


In [22]:
# Total number of pixels is accessed by img.size
print (img.size)

1555200


In [23]:
# Image datatype is obtained by img.dtype
print (img.dtype)

uint8


In [27]:
# Splitting and Merging Image Channels
b = img[:,:,0]
g = img[:,:,1]
r = img[:,:,2]
print (b)
print (g)
print (r)

[[122 122 123 ... 123 123 123]
 [122 122 122 ... 123 123 123]
 [122 122 122 ... 123 123 123]
 ...
 [154 156 153 ... 180 181 181]
 [162 160 152 ... 174 175 176]
 [156 148 137 ... 161 162 162]]
[[185 185 186 ... 184 184 184]
 [185 185 185 ... 184 184 184]
 [185 185 185 ... 184 184 184]
 ...
 [166 168 165 ... 197 198 198]
 [174 172 164 ... 192 193 194]
 [168 160 149 ... 179 180 180]]
[[229 229 230 ... 229 229 229]
 [229 229 229 ... 229 229 229]
 [229 229 229 ... 229 229 229]
 ...
 [154 156 153 ... 181 182 182]
 [164 162 154 ... 176 177 178]
 [158 150 139 ... 163 164 164]]


In [28]:
# Suppose, you want to make all the red pixels to zero, 
# you need not split like this and put it equal to zero. You can simply use Numpy indexing which is faster.
img[:,:,2] = 0
print (img)

[[[122 185   0]
  [122 185   0]
  [123 186   0]
  ...
  [123 184   0]
  [123 184   0]
  [123 184   0]]

 [[122 185   0]
  [122 185   0]
  [122 185   0]
  ...
  [123 184   0]
  [123 184   0]
  [123 184   0]]

 [[122 185   0]
  [122 185   0]
  [122 185   0]
  ...
  [123 184   0]
  [123 184   0]
  [123 184   0]]

 ...

 [[154 166   0]
  [156 168   0]
  [153 165   0]
  ...
  [180 197   0]
  [181 198   0]
  [181 198   0]]

 [[162 174   0]
  [160 172   0]
  [152 164   0]
  ...
  [174 192   0]
  [175 193   0]
  [176 194   0]]

 [[156 168   0]
  [148 160   0]
  [137 149   0]
  ...
  [161 179   0]
  [162 180   0]
  [162 180   0]]]


In [31]:
# comparing the image pixel
compare_pixel = 170
thresholds = img[:,:,0] < compare_pixel
print (thresholds)

[[ True  True  True ...  True  True  True]
 [ True  True  True ...  True  True  True]
 [ True  True  True ...  True  True  True]
 ...
 [ True  True  True ... False False False]
 [ True  True  True ... False False False]
 [ True  True  True ...  True  True  True]]


In [34]:
# replce the original image with the threshold value . Those who are less than the compare_pixel will be stays as same
img[thresholds] = [2,1,0]
print(img)

[[[  2   1   0]
  [  2   1   0]
  [  2   1   0]
  ...
  [  2   1   0]
  [  2   1   0]
  [  2   1   0]]

 [[  2   1   0]
  [  2   1   0]
  [  2   1   0]
  ...
  [  2   1   0]
  [  2   1   0]
  [  2   1   0]]

 [[  2   1   0]
  [  2   1   0]
  [  2   1   0]
  ...
  [  2   1   0]
  [  2   1   0]
  [  2   1   0]]

 ...

 [[  2   1   0]
  [  2   1   0]
  [  2   1   0]
  ...
  [180 197   0]
  [181 198   0]
  [181 198   0]]

 [[  2   1   0]
  [  2   1   0]
  [  2   1   0]
  ...
  [174 192   0]
  [175 193   0]
  [176 194   0]]

 [[  2   1   0]
  [  2   1   0]
  [  2   1   0]
  ...
  [  2   1   0]
  [  2   1   0]
  [  2   1   0]]]


In [51]:
# Basic python int tupple
test = [1, 2, 5]
print (test)   


[1, 2, 5]
